---
- name: Carvisor install
  hosts: all
  remote_user: root

  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
      become: yes
      become_method: sudo
    - name: Install essential
      apt:
        pkg:
        - git
        - python3
        - python3-apt
        - python3-pip
        - vim
        - libnfc6
        - libnfc-bin
        - libnfc-examples
        - bluez
        state: latest
        update_cache: true
      become: yes
      become_method: sudo
    - name: Pip install packages
      become: yes
      become_user: root
      pip:
        name:
          - flask
          - numpy
          - tinydb
          - pyserial
          - pint
          - pynmea2
          - pybluez
        executable: pip3
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/src/carvisor
        state: directory
        mode: '0755'
      become: yes
      become_method: sudo
    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/MarcinKwapisz/carvisor-iotapp.git
        dest: /usr/src/carvisor
        clone: yes
      become: yes
      become_method: sudo
    - name: Make Carvisor start file executable
      ansible.builtin.file:
        path: /usr/src/carvisor/start_carvisor.sh
        state: touch
        mode: u=rwx,g=r,o=r
      become: yes
      become_method: sudo
    - name: Make Carvisor BT file executable
      ansible.builtin.file:
        path: /usr/src/carvisor/BTStart.sh
        state: touch
        mode: u=rwx,g=r,o=r
      become: yes
      become_method: sudo
    - name: Copy Carvisor service file
      ansible.builtin.copy:
        src: templates/carvisor.service.j2
        dest: /lib/systemd/system/carvisor.service
        owner: root
        mode: u+rwx,g-wx,o-rwx
      become: yes
      become_method: sudo
    - name: Copy NFC config file
      ansible.builtin.copy:
        src: templates/libnfc.conf.j2
        dest: /etc/nfc/libnfc.conf
        owner: root
        mode: u+rwx,g-wx,o-rwx
      become: yes
      become_method: sudo
    - name: Copy Carvisor API service file
      ansible.builtin.copy:
        src: templates/carvisorAPI.service.j2
        dest: /lib/systemd/system/carvisorAPI.service
        owner: root
        mode: u+rwx,g-wx,o-rwx
      become: yes
      become_method: sudo
    - name: Carvisor | Start Carvisor service
      ansible.builtin.service:
        name: carvisor.service
        state: started
        enabled: yes
      become: yes
      become_method: sudo
    - name: Carvisor | Start Carvisor API service
      ansible.builtin.service:
        name: carvisorAPI.service
        state: started
        enabled: yes
      become: yes
      become_method: sudo
