--- Carvisor IoT playbook

- name: BASIC INSTALL
  with_items: groups['all']
  become: yes
  gather_facts: yes

  tasks:
    - name: Upgrade all apt packages
       apt: upgrade=dist force_apt_get=yes
    - name: Install essential
      apt:
        pkg:
          - git
          - setuptools
          - python3
          - python3-apt
          - pyton3-pip
          - python3-opencv
        state: latest
        update_cache: true
    - name: Pip install essential
      pip:
        virtualenv_command: /usr/bin/python3 -m venv
        name: flask numpy tinydb serial
        state: latest
    - name: Get Carvisor-IoT repo
      git:
          repo: git@github.com:MarcinKwapisz/carvisor-iotapp.git
          dest: /src/carvisor
          version: master
          accept_hostkey: yes
        become: yes
        become_user: root